apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configMapName | default (printf "%s-config" (include "wonderkids.fullname" .)) }}
  namespace: {{ .Values.namespace }}
  labels: {{ include "wonderkids.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}